from .config import (
    CHINESE_PROBE_TEXT,
    DASHSCOPE_API_KEY,
    DEFAULT_LANG,
    DEFAULT_MODEL,
    DEFAULT_PROBE_TEXT,
    DEFAULT_VOICE,
    MAX_CHARS_PER_REQ,
    MIN_CHARS_PER_REQ,
    MIN_TTS_MERGE_CHARS,
    PCM_FORMAT,
    PCM_SAMPLE_RATE,
    _load_env_file,
)
from .schemas import SessionState, TTSSpeakRequest
from .errors import TTSAllFailedError
from .text_utils import _is_chinese_text, _normalize_text, _split_text_for_tts, _text_bucket
from .audio_utils import _download_to_base64, _guess_audio_format, _guess_stream_audio_format, _guess_stream_sample_rate
from .voices import SUPPORTED_VOICES, VOICE_TYPE_TO_VOICE, normalize_voice
from .candidates import (
    TTS_CANDIDATES,
    _build_attempt,
    _cache_candidate_success,
    _candidate_matches_voice,
    _default_tts_candidates,
    _dedupe_candidates,
    _load_tts_candidates,
    _prioritize_candidates,
    _probe_attempts,
    _probe_bucket,
    _probe_cache,
    _probe_lock,
)
from .dashscope_client import (
    _call_multimodal_tts,
    _call_qwen_tts,
    _call_tts_candidate,
    _extract_audio_meta,
    _iter_dashscope_stream,
    _run_streaming_call,
    _safe_get,
)
from .synthesis import (
    _send_ws_fallback_audio,
    _ws_error_payload,
    _ws_send_json,
    stream_tts_with_candidates,
    synthesize_with_candidates,
)
from .routes import router, speak, ws_tts
from .app import app

__all__ = [
    'CHINESE_PROBE_TEXT',
    'DASHSCOPE_API_KEY',
    'DEFAULT_LANG',
    'DEFAULT_MODEL',
    'DEFAULT_PROBE_TEXT',
    'DEFAULT_VOICE',
    'MAX_CHARS_PER_REQ',
    'MIN_CHARS_PER_REQ',
    'MIN_TTS_MERGE_CHARS',
    'PCM_FORMAT',
    'PCM_SAMPLE_RATE',
    'SUPPORTED_VOICES',
    'SessionState',
    'TTSSpeakRequest',
    'TTSAllFailedError',
    'TTS_CANDIDATES',
    'VOICE_TYPE_TO_VOICE',
    '_build_attempt',
    '_cache_candidate_success',
    '_call_multimodal_tts',
    '_call_qwen_tts',
    '_call_tts_candidate',
    '_candidate_matches_voice',
    '_dedupe_candidates',
    '_default_tts_candidates',
    '_download_to_base64',
    '_extract_audio_meta',
    '_guess_audio_format',
    '_guess_stream_audio_format',
    '_guess_stream_sample_rate',
    '_is_chinese_text',
    '_iter_dashscope_stream',
    '_load_env_file',
    '_load_tts_candidates',
    '_normalize_text',
    '_prioritize_candidates',
    '_probe_attempts',
    '_probe_bucket',
    '_probe_cache',
    '_probe_lock',
    '_run_streaming_call',
    '_safe_get',
    '_send_ws_fallback_audio',
    '_split_text_for_tts',
    '_text_bucket',
    '_ws_error_payload',
    '_ws_send_json',
    'app',
    'normalize_voice',
    'router',
    'speak',
    'stream_tts_with_candidates',
    'synthesize_with_candidates',
    'ws_tts',
]
