plugins {
    id "com.android.application"
}

android {
    namespace "com.maozhishi.tablet"
    compileSdk 35
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "com.maozhishi.tablet"
        minSdk 21
        targetSdk 35
        versionCode 10
        versionName "0.10.0-vercel-proxy"
        buildConfigField "String", "DEFAULT_PAGE_URL", "\"https://vercel-proxy-nine-beta.vercel.app/tablet_legacy.html?singleOrigin=1&publicMode=1\""
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

